apply plugin: 'com.android.application'

android {
    compileSdkVersion 25

    defaultConfig {
        applicationId project.PACKAGE_NAME
        versionCode Integer.parseInt(project.VERSION_CODE)
        versionName project.VERSION_NAME
        minSdkVersion 16
        targetSdkVersion 22
        multiDexEnabled false
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    repositories {
        mavenCentral()
    }

    lintOptions {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:25.1.1'
    implementation 'com.android.support:support-v4:25.1.1'
    implementation 'com.android.support:design:25.1.1'


    implementation 'com.github.bumptech.glide:glide:3.6.1'

    implementation 'io.reactivex:rxandroid:1.1.0'
    implementation 'io.reactivex:rxjava:1.1.0'


    implementation 'com.daimajia.numberprogressbar:library:1.2@aar'

    implementation 'com.github.michael-rapp:android-bottom-sheet:1.3.0'
}
